version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 254675571356.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t demo-ecr .
      - docker tag demo-ecr:latest 254675571356.dkr.ecr.us-east-1.amazonaws.com/cdk-devsonlnv2-container-assets-254675571356-us-east-1:latest
  
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 254675571356.dkr.ecr.us-east-1.amazonaws.com/cdk-devsonlnv2-container-assets-254675571356-us-east-1:latest
      - echo '[{"name":"app-container","imageUri":"254675571356.dkr.ecr.us-east-1.amazonaws.com/cdk-devsonlnv2-container-assets-254675571356-us-east-1:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - appspec.yml
    - imagedefinitions.json
